### ISSUE TITLE
Deployment 1 of user auth

### ISSUE THREAD

**Issue by PLUCS2** [zbmike/32-em#4]
- [x] Add errors for improper credentials with login, not just for not putting something in
- [x] Get rid of blue border that appears around the button when clicking login or signup buttons 
- [x] Add a demo user login and demo login button 
- [x] Add a footer to splash page 
- [x] Add hover effect to login and signup (color change and cursor change)
- [x] make 32em logo on top left of splash page link back to splash page so you can get out of login/signup 
- [x] Profile picture button after logging in should have a dropdown to select logout from, not just logout 
- [x] Style splash page (should look like a real home page) 
- [x] Add hover effects to login and signup buttons on splash page

**Comment by zbmike** [comment]
Got them all
